### ISSUE TITLE
arangod log issues

### ISSUE THREAD

**Issue by pekeler** [triAGENS/ArangoDB#1226]
using 2.4.1 on a mac

I was running `arangod --javascript.dev-app-path foxx db` to develop a new Foxx app. At some point I made a mistake (I forgot to require a model in my controller) and my page didn't load anymore (`{"error":true,"code":404,"errorNum":404,"errorMessage":"unknown path 'dev/arango_react/index.html'"}`). This brings me to my first point: it would be nice if this error message was a bit closer to the actual cause.

There was no indication on stdout of any problem. So I restarted arangod and the stdout looked all good but I was puzzled why my app was gone now (from http://localhost:8529/_db/_system/_admin/aardvark/standalone.html#applications). After wasting some time trying to mount my app with foxxmanager, I come across arangod.log which shows the root cause of my problem (the missing require).

Shouldn't arangod print some sort of warning to stdout if it can't load the application?

 arangod --help claims that --log.file defaults to + but that is clearly not the case because if I start it up with `arangod --javascript.dev-app-path foxx --log.file + db` it is way more talkative.

However, even with `arangod --javascript.dev-app-path foxx --log.file + --log.level debug db` there's still no indication whatsoever about the bug in my application when starting up. Only when I make a request to my app do I see the error now (which I didn't realize immediately).

Long story to give you some beginner's feedback. The big issue that I think needs fixing is that either
- launching arangod without log parameters should log to stdout
- or `arangod --help` shouldn't claim + is the default, and all the tutorials should be updated to include `--log.file +`

**Comment by jsteemann** [comment]
Thanks for the feedback! I think you pointed us at two things which can be confusing for users.

I think there are a two issues to sort out:
* 404 errors are showing when a route that was called is not available. Among other things, non-availability can be caused by an issue in the JavaScript file that defines the routes. For example, if the file defining the routes contains a parse error, there is no way for ArangoDB to figure out which routes should have been there if it were correct. However, getting just a 404 isn't helpful during development. My suggestion to fix this is to install a special error route handler for any apps that cannot be mounted, for whatever reason. This error handler could print the exception (and stack trace) that was caught when trying to mount the app. This would be very helpful for developers from my point of view. @fceller, @mchacki: what do you think about this?
* when invoking `arangod --help` manually, it will print its defaults. The default for `--log-file` is `+` indeed. I think the confusion about ArangoDB not logging to stdout when started regularly arises because then it is given a config file, which has different settings for logging. I think the default config file contains the value `./log/arangodb/arangodb.log` so ArangoDB will log there when given the config file or started as a service. I admit this might be confusing. Obviously you don't want to log to stderr/stdout when ArangoDB is started as a service, but for development and manual starts it might be better to always have log messages printed on the console. Maybe a solution is to always log to stdout/stderr if arangod was started by a terminal, and use `--log.file` for additional, file-based logging only? @fceller, @mchacki: what do you think about this?

**Comment by mchacki** [comment]
To 1)
I totally agree with @jsteemann . Right now we are improving the foxx core for release 2.5 that also includes a much better error logging and also includes the fix described by @jsteemann . I have now backportet it to 2.4 and it will be shipped with the next bug-fix release.
To 2)
I also think it should make a difference if i start arangodb as a service in background or as a foreground task on my console. So i would also prefer: service => print to log, arangod => print to stdout.

**Comment by fceller** [comment]
I've changed the behaviour in devel as follows:

If arangod is start on a terminal in non-daemon mode, it will always log to stderr.

If you start arangod with "--help" it will print both the default and the current value, e. g.

    Logging Options
      --log.file <string>             log to file (default: "+", current: "emil")

**Comment by pekeler** [comment]
Nice. Thanks!
